{{- if .Values.webhook.enabled }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    {{- if .Values.webhook.certificate.create }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Values.webhook.certificate.name}}
    {{ else }}
    cert-manager.io/inject-ca-from-secret: {{ .Release.Namespace }}/{{ .Values.webhook.certificate.secretName}}
    {{- end }}
  labels:
    {{- include "labels" . | nindent 4 }}
    app.kubernetes.io/component: "webhook"
  name: {{ .Values.webhook.names.mutating }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "webhook.name" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-kinda-rocks-v1beta1-database
  failurePolicy: Fail
  name: mdatabase.kb.io
  rules:
  - apiGroups:
    - kinda.rocks
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - databases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "webhook.name" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-kinda-rocks-v1beta1-dbinstance
  failurePolicy: Fail
  name: mdbinstance.kb.io
  rules:
  - apiGroups:
    - kinda.rocks
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dbinstances
  sideEffects: None
{{- end }}
