{{- if .Values.webhook.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webhook.name" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
    app.kubernetes.io/component: "webhook"
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "webhook"
{{- end }}
