{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "db-operator.serviceAccountName" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
    app.kubernetes.io/component: "controller"
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 2 }}
{{- end }}
{{- end -}}
