values: |
  serviceAccount:
      create: false
  webhook:
    serviceAccount:
      create: false
files:
  - Certificate-db-operator-webhook.yml
  - ConfigMap-db-operator-config.yml
  - Deployment-db-operator.yml
  - Deployment-db-operator-webhook.yml
  - ClusterRoleBinding-db-operator.yml
  - CustomResourceDefinition-databases.kinda.rocks
  - Issuer-db-operator-issuer.yml
  - Service-db-operator-webhook.yml
  - ClusterRole-db-operator.yml
  - CustomResourceDefinition-dbinstances.kinda.rocks
  - CustomResourceDefinition-dbusers.kinda.rocks
  - MutatingWebhookConfiguration-db-operator-mutating-webhook-configuration.yml
  - ValidatingWebhookConfiguration-db-operator-validating-webhook-configuration.yml
